(function(g){var window=this;'use strict';var w4=function(a){a.ma("cardstatechange",a.nk()&&a.xo()?1:0)},x4=function(a,b){var c=g.Oa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},ydb=function(a){var b=g.Jm(a);
a=g.Mm(a);return new g.ym(b.x,b.y,a.width,a.height)},A4=function(a){a=g.Ra(a);
delete y4[a];g.bd(y4)&&z4&&z4.stop()},Adb=function(){z4||(z4=new g.Cp(function(){zdb()},20));
var a=z4;a.isActive()||a.start()},zdb=function(){var a=g.Va();
g.Sc(y4,function(b){Bdb(b,a)});
g.bd(y4)||Adb()},B4=function(a,b,c,d){g.Wp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.J=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.I=0;this.C=null},Bdb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.C);a.C=b;Cdb(a,a.progress);1==a.progress?(a.j=0,A4(a),a.onFinish(),a.Hq()):a.Zc()&&a.hJ()},Cdb=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.J[c]-a.u[c])*b+a.u[c]},Ddb=function(a,b){g.qb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.j},C4=function(a,b,c,d,e){B4.call(this,b,c,d,e);
this.element=a},Edb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
C4.call(this,a,b,c,d,e)},Fdb=function(a){return Math.pow(a,3)},Gdb=function(a){return 3*a*a-2*a*a*a},Hdb=function(a){g.E.call(this);
this.u=a||window;this.j=[]},D4=function(a){return a.baseUrl||null},E4=function(a,b){return g.Ln(g.Sl(a,b),function(c){return!!c})},Idb=function(a,b,c){function d(J){var ha=J.hovercardButton;
if(!ha)return null;ha=ha.subscribeButtonRenderer;if(!ha)return null;var Z=f(ha.unsubscribedButtonText),xa=f(ha.subscribedButtonText);if(ha.subscribed){var za=f(ha.subscriberCountWithUnsubscribeText);var Ya=f(ha.subscriberCountText)}else za=f(ha.subscriberCountText),Ya=f(ha.subscriberCountWithSubscribeText);var cb=null;if(J.signinEndpoint){cb=x4(J,"signinEndpoint","webNavigationEndpointData","url");if(!cb){var wa,$a;cb=null==($a=g.S(null==(wa=ha.signInEndpoint)?void 0:wa.commandMetadata,g.p3))?void 0:
$a.url}if(!cb)return null}return Z&&(xa||cb)?{subscribed:ha.subscribed,subscribeText:Z,subscribeCount:za,unsubscribeText:xa,unsubscribeCount:Ya,enabled:ha.enabled,signinUrl:cb,classic:J.useClassicSubscribeButton}:null}
function e(J){if(J){var ha=[],Z=J.videoId;Z&&ha.push("v="+Z);(Z=J.playlistId)&&ha.push("list="+Z);(J=J.startTimeSeconds)&&ha.push("t="+J);return"/watch?"+ha.join("&")}}
function f(J){if(!J)return null;var ha=J.simpleText;return ha?ha:J.runs?g.Sl(J.runs,function(Z){return Z.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,x=null,z=null,D=!1,G=null,O=null,N=null,K=null,W=null,Y=null;if("VIDEO"===h)g.S(l,g.kM)?m=g.S(l,g.kM).url:(Y=g.S(l,g.jM),m=e(Y)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===h)g.S(l,g.kM)?m=g.S(l,g.kM).url:(Y=g.S(l,g.jM),m=e(Y)),n=!1,q=a,x=f(b.playlistLength);else if("CHANNEL"===
h){if(D=x4(l,"browseEndpoint","browseId"))z=D,m="/channel/"+z;n=!1;q="new";(D=!!b.isSubscribe)?G=d(b):O=f(b.subscribersText)}else"WEBSITE"===h?((N=x4(l,"urlEndpoint","url"))&&(m=N),n=!0,q="new",N=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(K=f(b.productPrice)),b.additionalFeesText&&(W=f(b.additionalFeesText)),(n=x4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=x4(b,"title","accessibility","accessibilityData","label");var Q=b.endpoint?b.endpoint.clickTrackingParams:null,
na="";if(b.metadata){var r=f(b.metadata);r&&(na=r)}return{id:"element-"+c,type:h,title:f(b.title),metadata:na,callToAction:f(b.callToAction),mT:b.image,iconUrl:N,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,yC:p,playlistLength:x,channelId:z,subscribeButton:G,subscribersText:O,isSubscribe:D,Lt:m||null,L4:n,sessionData:Q?{itct:Q}:null,L9:q,XA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:E4(b.impressionUrls||[],D4),A4:E4(b.hovercardShowUrls||[],D4),clickUrls:E4(l.loggingUrls||[],D4),visualElement:g.wE(b.trackingParams),productPrice:K,additionalFeesText:W,watchEndpoint:Y||null}},Jdb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:E4(a.impressionUrls||[],D4),elements:E4(a.elements||[],function(d,e){return Idb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.wE(a.trackingParams));return c},Kdb=function(a){g.vT.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.ea=!0;this.I=0;a=a.V();this.T=g.gK(a)||"profilepage"===a.Ga;this.events=new g.NH(this);g.I(this,this.events);this.events.S(this.player,g.UD("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.VD("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.Db);this.events.S(window,"focus",this.t8);this.load();var b=g.$e("STYLE");(g.Re("HEAD")[0]||document.body).appendChild(b);g.nb(this,
function(){g.pf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Ldb=function(a){return a.player.getVideoData().D?"current":a.T?"new":"current"},F4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},Mdb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Jdb(f,Ldb(a))));G4(a,f)},
urlParams:{v:c},withCredentials:!0};a.T&&(c.urlParams.ptype="embedded");var d=b.kx;d&&(c.postParams={ad_tracking:d});if(b=g.Wza(b))if(b=g.ae(b),b=g.Zd(b))a.B=g.By(b,c)},G4=function(a,b,c){c=void 0===c?!0:c;
a.player.gf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&Ndb(a);c=[];d=new g.SD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().u||(a.u=new g.V({G:"div",N:"ytp-ce-shadow"}),g.GS(a.player,a.u.element,4),a.C=new g.MQ(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Odb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.GS(a.player,f.element,4);var h=new g.SD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Pdb(a,f,e)}else g.yD(new g.Wz("buildEndscreenElement null",
e))}a.player.ye(c);a.Db()}},Ndb=function(a){var b=g.zE(),c=g.AE();
c&&b&&a.endscreen.visualElement&&g.gy(g.YO)(void 0,c,b,a.endscreen.visualElement)},Odb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ia:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.XA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:H4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:I4(a,b.Lt),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.$p(b.title||"")},ra:b.title},{G:"div",N:b.yC?"ytp-ce-live-video-duration":"ytp-ce-video-duration",ra:b.videoDuration||
void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={G:"div",Ia:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.XA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:H4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:I4(a,b.Lt),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.$p(b.title||"")},ra:b.title},{G:"div",N:"ytp-ce-playlist-count",W:[{G:"div",N:"ytp-ce-playlist-icon"},
{G:"div",N:"ytp-ce-playlist-count-text",ra:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.XA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",
N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"a",Ia:["ytp-ce-channel-title","ytp-ce-link"],X:{href:I4(a,b.Lt),target:"_blank",tabindex:"-1",dir:g.$p(b.title||"")},ra:b.title},b.subscribeButton?{G:"div",N:"ytp-ce-subscribe-container",W:[{G:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",N:"ytp-ce-channel-subscribers-text",ra:b.subscribersText}:"",b.metadata?{G:"div",Ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
ra:b.metadata}:""]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:H4(b)}]};c=new g.V(c);var d=g.Se(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Kp(d,"ytp-ce-subscribe-button");if(a.player.V().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.jU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={G:"div",Ia:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.XA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",N:"ytp-ce-expanding-overlay-body",W:[{G:"div",
N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-website-title",X:{dir:g.$p(b.title||"")},ra:b.title},{G:"div",N:"ytp-ce-website-metadata",ra:b.metadata},{G:"a",Ia:["ytp-ce-website-goto","ytp-ce-link"],X:{href:I4(a,b.Lt),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:H4(b)},{G:"div",N:"ytp-ce-expanding-icon",X:Qdb(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",N:"ytp-ce-merchandise-price-container",
W:[{G:"div",N:"ytp-ce-merchandise-price",ra:b.productPrice}]},b.additionalFeesText&&c.W.push({G:"div",N:"ytp-ce-merchandise-additional-fees",ra:b.additionalFeesText})),a={G:"div",Ia:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.XA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",
W:[{G:"div",N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-merchandise-title",X:{dir:g.$p(b.title||"")},ra:b.title},c,{G:"div",N:"ytp-ce-merchandise-metadata",ra:b.metadata},{G:"a",Ia:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:I4(a,b.Lt),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:H4(b)},{G:"div",N:"ytp-ce-merchandise-invideo-cta-container",W:[{G:"div",N:"ytp-ce-merchandise-invideo-cta",
ra:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.Kp(c.element,"ytp-ce-placeholder");return c},H4=function(a){if(a.mT)var b=a.mT.thumbnails;
return Qdb(b?b[b.length-1].url:null)},Qdb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Pdb=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.Kp(b.element,"ytp-ce-force-expand"),J4(a,c.id,!0)):(g.Mp(b.element,"ytp-ce-force-expand"),g.Mp(b.element,"ytp-ce-element-hover"),J4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){Rdb(a,b,c)});
b.Ra("mouseleave",function(){Sdb(a,b,c)});
a.player.V().u||b.Ra("click",function(){g.Kp(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){Tdb(a,c,m)});
b.Ra("keypress",function(m){Tdb(a,c,m)});
b.Ra("focus",function(){Rdb(a,b,c)});
b.Ra("blur",function(){Sdb(a,b,c)});
b.Ra("touchstart",function(){Rdb(a,b,c)});
var l=g.Ue("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){g.uO?m.stopPropagation():(m=m||window.event,m.cancelBubble=!0,m.stopPropagation&&m.stopPropagation());g.Mp(b.element,"ytp-ce-element-hover");g.Mp(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.Ue("ytp-sb-subscribe",b.element));d(g.Ue("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},Tdb=function(a,b,c){if(b.Lt&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Jp(d,"ytp-ce-element");){g.Jp(d,"subscribe-label")&&Udb(a,b);
if(g.Jp(d,"ytp-ce-channel-subscribe"))return;d=g.qf(d)}if(!d||g.Jp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Sdb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.L9)Udb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.ae(I4(a,b.Lt)),g.DN(g.Zd(c),void 0,b.sessionData);else{var e=g.yK(a.player.V())||a.player.getVideoData().D,f=function(){var h=I4(a,b.Lt),l=b.sessionData,m=b.watchEndpoint,n=g.my(h);e&&n&&(n.v||n.list)?a.player.Kn(n.v,
l,n.list,!1,void 0,m||void 0):g.BN(h,l)};
Udb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},I4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.HK(a)+b}else return"";return b},Rdb=function(a,b,c){g.Jp(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Kp(b.element,"ytp-ce-element-hover"):a.player.V().u?(new g.Cp(function(){g.Kp(b.element,"ytp-ce-element-hover")},200)).start():g.Kp(b.element,"ytp-ce-element-hover"),K4(a,c.A4),J4(a,c.id,!0))},Sdb=function(a,b,c){g.Mp(b.element,"ytp-ce-element-hover");
g.Mp(b.element,"ytp-ce-force-expand");J4(a,c.id,!1)},J4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Op(a.j[e].element,"ytp-ce-element-shadow-show",c)},K4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||F4(a))c&&c();else{b=Vdb(a,b);var e=0,f=!1,h=new g.Cp(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.TB(b[a],d)}},Udb=function(a,b,c){K4(a,b.clickUrls,c);
(a=g.AE())&&b.L4&&g.gP(a,b.visualElement)},Vdb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Wdb(b[d],c));return a},Wdb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Xdb=function(a){return"string"===typeof a?a:""},L4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Ydb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},M4=function(a){return a.value?a.value:null},N4=function(a){if(!a)return null;
var b=g.ae(Xdb(a.value));b=g.Zd(b);if(!b)return null;var c=L4(a.target,Zdb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Ydb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},$db=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},ceb=function(a){if(!a)return null;
var b=L4(a.type,aeb),c=L4(a.trigger,beb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=N4(a?a:null);return b?new $db(b,c,a):null},deb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},eeb=function(a,b){return g.ub(a.action,b)},feb=function(a,b){this.context=a;
this.j=b},geb=function(a){return a.customMessage?O4("div","iv-card-message",a.customMessage):""},P4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",N:"iv-card-image",X:{style:a},W:c}},heb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(O4("li","",c.value));return{G:"ul",N:"iv-card-meta-info",W:b}},O4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.$p(c);return{G:a,X:b,ra:c}},ieb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.iB&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.iB+");");c.dir=g.$p(a.customMessage);var d=[{G:"span",ra:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",N:"iv-card-link-icon"}));return{G:"div",Ia:b,X:c,W:d}},Q4=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Mi.click,5)}},jeb=function(a,b){this.merchant=a;
this.price=b},keb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},leb=function(a,b){return b?b:keb(a)?"current":"new"},R4=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.sb=!1;this.Ya=new Map;this.fb=new Map;this.context.F.addEventListener(g.UD("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)});
this.context.F.addEventListener(g.VD("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},S4=function(a,b,c,d,e,f,h){a.context.j.Ra(b,"click",function(l){a.iJ(c,d,e,f||[],h||0,l)});
a.context.j.Ra(b,"touchstart",function(){a.sb=!1});
a.context.j.Ra(b,"touchmove",function(){a.sb=!0})},meb=function(a){var b;
return(null==(b=g.S(a,g.kM))?0:b.url)?g.S(a,g.kM).url:(a=g.S(a,g.jM))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},T4=function(a,b,c){return{JU:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
gY:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
pI:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},neb=function(a,b,c){R4.call(this,b,c);
var d=this;this.F=a;this.eventId=null;this.La=this.Sb=this.B=this.isInitialized=!1;this.cards=[];this.Pb=this.T=this.Ja=this.D=this.Wa=this.j=null;this.Z=[];this.oa=this.J=this.Zf=this.Ga=null;this.I=0;this.Aa=new g.Cp(function(){},c.Y.oh?4E3:3E3);
g.I(this,this.Aa);this.kb=new g.Cp(function(){});
g.I(this,this.kb);this.ya=new feb(c,function(e,f,h,l,m,n){S4(d,e,f,h,l,m,n)});
this.ea=new g.V({G:"div",N:"iv-drawer",X:{id:"iv-drawer"},W:[{G:"div",N:"iv-drawer-header",X:{"aria-role":"heading"},W:[{G:"span",N:"iv-drawer-header-text"},{G:"button",Ia:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"Nascondi schede",tabindex:"0"}}]},{G:"div",N:"iv-drawer-content"}]});g.I(this,this.ea);this.C=this.ea.element;this.ib=new g.MQ(this.ea,330);g.I(this,this.ib);this.Tb=g.Ue("iv-drawer-header-text",this.C);this.u=g.Ue("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Sb&&U4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Sb=d.B)&&V4(d)});
this.Oa=new g.NH(this);g.I(this,this.Oa);this.F.addEventListener("videodatachange",this.Hs.bind(this))},oeb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){U4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){V4(a)});
var c=b.headerText;g.sf(a.Tb,c);a.T&&a.T.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.wE(b.trackingParams);a.J=g.wE(b.closeTrackingParams);a.Zf=g.wE(b.iconTrackingParams)},peb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.F.V().experiments.ob("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.bE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Mi:{},zo:null,Yk:e.trackingParams?g.wE(e.trackingParams):null,Zf:f&&f.trackingParams?g.wE(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
iB:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};W4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.bE(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:X4(a,c,b,f),sponsored:!1,Mi:T4(f,e,f.command),zo:f.trackingParams?g.wE(f.trackingParams):null,Yk:e.trackingParams?g.wE(e.trackingParams):null,Zf:l&&l.trackingParams?g.wE(l.trackingParams):null,imageUrl:Y4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.bE(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,iB:null,title:f.title?g.bE(f.title):"",customMessage:f.callToAction?g.bE(f.callToAction):"",url:g.S(f.command,g.kM).url?N4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(f.command,g.kM).url}):null,onClickCommand:null};W4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.bE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:X4(a,c,b,e),sponsored:!1,Mi:T4(e,f,e.endpoint),zo:e.trackingParams?g.wE(e.trackingParams):null,Yk:f.trackingParams?g.wE(f.trackingParams):null,Zf:l&&l.trackingParams?g.wE(l.trackingParams):null,channelId:g.S(e.endpoint,Z4).browseId,customMessage:e.customText?g.bE(e.customText):null,cX:Y4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.bE(e.channelName):"",metaInfo:[e.subscriberCountText?g.bE(e.subscriberCountText):""],url:N4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(e.endpoint,Z4).canonicalBaseUrl?g.S(e.endpoint,Z4).canonicalBaseUrl:"/channel/"+g.S(e.endpoint,Z4).browseId}),onClickCommand:null};W4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.bE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:X4(a,c,b,e),sponsored:!1,Mi:T4(e,f,e.action),zo:e.trackingParams?g.wE(e.trackingParams):null,Yk:f.trackingParams?g.wE(f.trackingParams):null,Zf:l&&l.trackingParams?g.wE(l.trackingParams):null,gE:Y4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.bE(e.customMessage):null,playlistVideoCount:g.bE(e.playlistVideoCount),title:e.playlistTitle?g.bE(e.playlistTitle):"",metaInfo:[e.channelName?g.bE(e.channelName):
"",e.videoCountText?g.bE(e.videoCountText):""],url:N4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:meb(e.action)}),onClickCommand:null};W4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.bE(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:X4(a,c,b,e),sponsored:!1,Mi:T4(e,f,e.action),zo:e.trackingParams?g.wE(e.trackingParams):null,Yk:f.trackingParams?g.wE(f.trackingParams):null,Zf:l&&l.trackingParams?g.wE(l.trackingParams):null,gE:Y4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.bE(e.lengthString):null,customMessage:e.customMessage?g.bE(e.customMessage):null,title:e.videoTitle?g.bE(e.videoTitle):"",metaInfo:[e.channelName?g.bE(e.channelName):
"",e.viewCountText?g.bE(e.viewCountText):""],isLiveNow:!!e.badge,url:N4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:meb(e.action)}),onClickCommand:null};W4(a,b)}}}}}a.I++},Y4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},X4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},reb=function(a,b){if(b=qeb(a,b))b===a.j&&(a.j=null),a.F.removeCueRange(b.og.id),g.pf(b.MK),g.Ab(a.cards,b),a.bF(),$4(a)},U4=function(a,b,c){if(!a.B){a.ib.show();
a.Wa=new g.Cp(function(){g.Kp(a.context.F.getRootNode(),g.UW.IV_DRAWER_OPEN)},0);
a.Wa.start();a.Oa.S(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.AE();d&&a.Ga&&a.J&&g.eP(d,[a.Ga,a.J]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.vV||(f.vV=!0,seb(a.context.logger,f.og.Mi.JU,b)),d&&g.eP(d,[f.og.zo]);w4(a.F);c&&(a.D=new g.Cp(function(){a.Ja=a.T;a.Pb.focus()},330),a.D.start())}},V4=function(a){a.B&&(a.ib.hide(),g.Fz(a.Oa),g.Mp(a.context.F.getRootNode(),g.UW.IV_DRAWER_OPEN),a.B=!1,w4(a.F),a.D&&a.D.stop(),a.D=new g.Cp(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},ueb=function(a){g.Lp(a.ub(),
[g.UW.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.GS(a.F,a.C,5);teb(a);a.T=g.Ue("ytp-cards-button",a.F.getRootNode());a.Pb=g.Ue("iv-drawer-close-button",a.C);a.isInitialized=!0},teb=function(a){var b=g.Ue("iv-drawer-close-button",a.C);
a.context.j.Ra(b,"click",a.Q2,a);a.context.j.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.j.Ra(a.u,"scroll",a.l3,a);a.context.u.subscribe("onHideControls",function(){a.La=!0});
a.context.u.subscribe("onShowControls",function(){a.La=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.La=g.Jp(a.F.getRootNode(),"ytp-autohide")});
a.Z.push(g.jC("iv-button-shown",a.V4,a));a.Z.push(g.jC("iv-button-hidden",a.U4,a));a.Z.push(g.jC("iv-teaser-shown",a.RZ,a));a.Z.push(g.jC("iv-teaser-hidden",a.W4,a));a.Z.push(g.jC("iv-teaser-clicked",a.QZ,a))},veb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.S(b.onClickCommand,g.lab))?void 0:c.targetId)?(a.oa=b,!0):!1},web=function(a,b){a.oa=b;
var c=a.F.getVideoData();if(!c)return!1;c=a.F.K("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.DL(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.S(h[0],g.gPa))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}return!1},
W4=function(a,b){if(!veb(a,b)||web(a,b)){var c=xeb(a,b);
if(c){var d={og:b,MK:c.element,vV:!1};if(!b.onClickCommand){a.isInitialized||ueb(a);reb(a,b.id);var e=yeb(a,d);g.Jb(a.cards,e,0,d);c.Ea(a.u,e);a.bF()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,$4(a),zeb(a,d),U4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.F.getCurrentTime(),5E3>c&&c>b.startMs&&Aeb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Aeb(a,d)}),$4(a))}}},xeb=function(a,b){switch(b.type){case "simple":a=a.ya;
var c=b.displayDomain?{G:"div",N:"iv-card-image-text",ra:b.displayDomain}:void 0;var d=ieb(b);c={G:"div",Ia:["iv-card"],W:[{G:"a",N:"iv-click-target",X:{href:b.url?M4(b.url)||"":""},W:[P4(b.imageUrl,c),{G:"div",N:"iv-card-content",W:[O4("h2",void 0,b.title),d]}]}]};c=new g.V(c);Q4(a,g.Te("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.ya;c={G:"div",Ia:["iv-card","iv-card-channel"],W:[{G:"a",Ia:["iv-click-target"],X:{href:M4(b.url)||"","data-ytid":b.channelId},W:[P4(b.cX),{G:"div",
N:"iv-card-content",W:[geb(b),{G:"h2",N:"iv-card-primary-link",ra:b.title},heb(b)]}]}]};c=new g.V(c);Q4(a,g.Te("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.ya;c={G:"div",Ia:["iv-card","iv-card-playlist"],W:[{G:"a",N:"iv-click-target",X:{href:M4(b.url)||""},W:[P4(b.gE,{G:"div",N:"iv-card-image-overlay",W:[{G:"span",N:"iv-card-playlist-video-count",ra:b.playlistVideoCount}]}),{G:"div",N:"iv-card-content",W:[geb(b),O4("h2","iv-card-primary-link",b.title),heb(b)]}]}]};c=new g.V(c);
Q4(a,g.Te("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.ya;var e=!g.xb(b.offers);c=["iv-card"];d="";var f=ieb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",N:"iv-card-offer-price",ra:f.price}),f.merchant&&e.push({G:"div",N:"iv-card-offer-merchant",ra:f.merchant}),f={G:"div",W:e});e=b.url?M4(b.url)||"":"";c={G:"div",Ia:c,X:{tabindex:"0"},W:[{G:"a",Ia:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",N:"iv-card-content",W:[b.sponsored?{G:"div",N:"iv-card-sponsored",W:["Sponsorizzati",{G:"div",N:"iv-ad-info-container",W:[{G:"div",N:"iv-ad-info",ra:"{{adInfo}}"},{G:"div",N:"iv-ad-info-icon-container",W:[{G:"div",N:"iv-ad-info-icon"},{G:"div",N:"iv-ad-info-callout"}]}]}]}:"",{G:"a",N:"iv-click-target",X:{href:e},W:[O4("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.$e("span");g.sf(d,"Visualizzi questo prodotto perch\u00e9 riteniamo sia attinente al video. Google potrebbe ricevere un compenso da parte del commerciante.");
c.ge(d,"adInfo");Q4(a,g.Te("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.ya;d=b.videoDuration?{G:"span",N:"iv-card-video-duration",ra:b.videoDuration}:void 0;f=b.isLiveNow?{G:"span",Ia:["yt-badge","yt-badge-live"],ra:"IN DIRETTA ORA"}:null;e={G:"div",Ia:["iv-card","iv-card-video"],W:[{G:"a",N:"iv-click-target",X:{href:(null==(c=b.url)?void 0:M4(c))||""},W:[P4(b.gE,d),{G:"div",N:"iv-card-content",W:[geb(b),O4("h2","iv-card-primary-link",b.title),heb(b),f]}]}]};c=new g.V(e);Q4(a,
g.Te("iv-click-target",c.element),b,b.url);b=c;break;default:return null}return b},yeb=function(a,b){if(0===a.cards.length)return 0;
a=g.vb(a.cards,function(c){return b.og.startMs>c.og.startMs||b.og.startMs===c.og.startMs&&b.og.timestamp>=c.og.timestamp?!0:!1});
return-1===a?0:a+1},Beb=function(a){return a.j?"productListing"===a.j.og.type:g.Tl(a.cards,function(b){return"productListing"===b.og.type})},$4=function(a){g.Op(a.F.getRootNode(),"ytp-cards-shopping-active",Beb(a))},Aeb=function(a,b){if(!g.Jp(a.F.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.AE(),d=a.j?a.j.og.Zf:a.Zf;
c&&d&&g.fP(c,[d]);a.j=b;$4(a)}(c=a.isInitialized&&"none"==a.ub().style.display)||(c=a.context.F.getPlayerState(),d=0===c&&0===a.context.F.getCurrentTime(),c=!(1===c||3===c||d));c||b.og.teaserDurationMs&&a.F.Qz(!0,{teaserText:b.og.teaserText,durationMs:b.og.teaserDurationMs,onClickCommand:b.og.onClickCommand});a.kb.isActive()||((!a.B||!a.Aa.isActive()&&a.La)&&zeb(a,b),a.kb.start(910+b.og.teaserDurationMs))}},zeb=function(a,b){a.ea.yb?(b=new B4([0,
a.u.scrollTop],[0,b.MK.offsetTop],600,Gdb),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.YP(a.ea,!0),a.u.scrollTop=b.MK.offsetTop,g.YP(a.ea,!1))},a5=function(a){return a.j&&a.j.og?a.j.og:a.cards[0]&&a.cards[0].og?a.cards[0].og:null},qeb=function(a,b){return g.ub(a.cards,function(c){return c.og.id===b})},b5=function(a,b,c){R4.call(this,a,b);
this.annotation=c;this.isActive=!1},Ceb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},c5=function(a,b,c){b5.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},Deb=function(a,b){var c=void 0===c?0:c;
var d=ydb(b).width;g.Hm(b,d);c=new Edb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Fdb);g.I(a,c);a.context.B.Ra(c,"begin",function(){g.Nm(b,!0)});
c.play()},Geb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ia:["iv-branding-context-name"],ra:b.channel_name}),d=a.createElement({G:"div",Ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.jU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.F),a.j.Ea(d));var f=a.createElement({G:"div",Ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ia:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Nm(h,!1);var l=a.createElement({G:"div",Ia:["branding-context-container-outer"]});l.appendChild(h);g.Bm(l,"right",b.image_width+"px");g.mf(a.ub(),l);a.B=new g.Cp(function(){Eeb(a,h,l)},500);
g.I(a,a.B);a.context.j.Ra(a.ub(),"mouseover",function(){Feb(a,h,l,f,b.image_height)});
a.context.j.Ra(a.ub(),"mouseout",function(){a.B.start()})}},Feb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Mm(b);a.j||(b.style.width=g.Gm(f.width,!0),c.style.width=g.Gm(f.width,!0));g.Bm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Bm(d,"right","1px");a.C=!0;g.Nm(b,!0);a.D=new g.Cp(function(){g.Kp(this.ub(),"iv-branding-active")},0,a);
a.D.start()}},Eeb=function(a,b,c){g.Mp(a.ub(),"iv-branding-active");
a.I=new g.Cp(function(){g.Nm(b,!1);a.j||(c.style.width=g.Gm(0,!0))},250);
a.I.start();a.C=!1},Heb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.F=f;this.u=h},Ieb=function(a,b,c){b5.call(this,a,b,c);
var d=this;this.T=this.isCollapsed=this.ea=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({G:"div",Ia:["iv-promo-contents"]});this.D=new g.Cp(function(){d.j.setAttribute("aria-hidden","true");g.Nm(d.B,!1);g.Nm(d.u,!0)},700,this);
g.I(this,this.D)},Keb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.ub().setAttribute("aria-hidden","true");a.ub().setAttribute("aria-label","Promozione");a.ub().tabIndex=0;var e=a.annotation.Ye(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",N:"iv-promo-video-duration",ra:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",N:"iv-promo-playlist-length",ra:b.playlist_length.toString()}),h.appendChild(f));e&&S4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",N:"iv-promo-txt"}),g.le(f,M4(e)),a.j=f):a.j=a.createElement({G:"div",N:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",W:[{G:"strong",ra:b.text_line_1}]});
var m=a.createElement({G:"p",W:[{G:"span",N:"iv-promo-link",ra:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ia:["iv-button","iv-promo-button"],W:[{G:"span",N:"iv-button-content",ra:f}]});var p=a.createElement({G:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&S4(a,a.ub(),e,a.annotation.id,b.session_data,void 0,c)}g.Kp(a.j,"iv-click-target");
e&&S4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",W:[{G:"span",ra:b.text_line_1}]}),m=a.createElement({G:"p",W:[{G:"strong",ra:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ia:["yt-badge","iv-promo-badge-live"],ra:"IN DIRETTA ORA"})),g.Kp(a.j,"iv-click-target"),e&&S4(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);
c=a.createElement({G:"div",N:"iv-promo-actions"});a.u=a.createElement({G:"button",Ia:["iv-promo-expand","ytp-button"]});a.u.title="Espandi";a.context.j.Ra(a.u,"click",function(q){Jeb(a,5E3,q)});
c.appendChild(a.u);g.Nm(a.u,!1);a.context.j.Ra(a.ub(),"mouseover",a.e4,a);a.context.j.Ra(a.ub(),"mouseout",a.d4,a);a.context.j.Ra(a.ub(),"touchend",function(q){Jeb(a,5E3,q)});
a.B=a.createElement({G:"button",Ia:["iv-promo-close","ytp-button"]});a.B.title="Chiudi";a.context.j.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.Y3:a.X3,a);c.appendChild(a.B);g.Lp(a.ub(),d);h&&(g.mf(a.ub(),h),n&&h.appendChild(n));g.mf(a.ub(),a.J);g.mf(a.ub(),c)},Jeb=function(a,b,c){c.stopPropagation();
Leb(a);Meb(a,b);a.j.focus()},Neb=function(a){a.isCollapsed||a.T||a.C||(g.Kp(a.ub(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},Leb=function(a){a.D.stop();
a.isCollapsed&&(g.Np(a.ub(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Nm(a.u,!1),g.Nm(a.B,!0))},Meb=function(a,b){a.C||(a.C=g.Qf(function(){Oeb(this);
Neb(this)},b,a))},Oeb=function(a){a.C&&(g.Ja.clearTimeout(a.C),a.C=null)},Peb=function(a){this.F=a},seb=function(a,b,c){b&&(c?d5(a,b.map(function(d){return g.rp(d,c)})):d5(a,b))},d5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.TB(m,f);d&&(e++,0!==d&&a.F.sendVideoStatsEngageEvent(d,f))},Qeb=function(a){g.vT.call(this,a);
var b=this;this.Z=this.J=!1;this.loadNumber=0;this.I={};this.logger=new Peb(this.player);this.C=new g.NH(this);this.D=this.zw=null;this.events=new g.NH(this);this.T=this.j=null;this.ea=[];g.I(this,this.C);this.C.S(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.C.S(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.C.S(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.C.S(this.player,"resize",function(d){b.ma("resize",d)});
this.C.S(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.SZ,this);this.subscribe("resize",this.eH,this);this.player.V().Aa.subscribe("vast_info_card_add",this.KW,this);g.I(this,this.events);this.oa=this.createElement({G:"div",N:"video-custom-annotations"});this.u=new g.V({G:"div",Ia:["ytp-player-content","ytp-iv-player-content"]});g.I(this,this.u);g.GS(this.player,this.u.element,4);this.u.hide();this.B=new g.V({G:"div",Ia:["ytp-iv-video-content"]});g.I(this,this.B);a=this.createElement({G:"div",N:"video-annotations"});
a.appendChild(this.oa);this.B.element.appendChild(a);this.lw()&&this.load();var c=this.createElement({G:"style"});(g.Re("HEAD")[0]||document.body).appendChild(c);g.nb(this,function(){g.pf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Reb=function(a){a=a.createElement({G:"div",
Ia:["annotation","annotation-type-custom"]});g.Nm(a,!1);return a},Seb=function(a,b){b=!b.isCued()&&!g.MN(b,1024);
g.YP(a.u,b);g.YP(a.B,b)},Teb=function(a,b,c){a.J=!0;
a.D=g.By(b,c)},Ueb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Ueb(a,e))}return c},Yeb=function(a){var b=a.player.getVideoData();
if(b.Wa){var c=a.player.V().Aa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.uy(h)&&h.responseXML?h.responseXML:null)&&Veb(a,h)}};
g.dA()&&(d.onFinish=Web(a,d.onFinish));d.postParams={ic_only:"1"};Xeb(d,c);a.J=!0;g.By(b.Wa,d)}}},Xeb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.kB&&(a.postParams.ic_coll=b.kB);b.NK&&(a.postParams.ic_xml=b.NK);b.sI&&(a.postParams.ic_track=b.sI)},Zeb=function(a){var b=new g.V({G:"div"});
g.Nm(b.element,!1);var c=new neb(a.player,b.element,e5(a));g.I(c,b);b.Ea(a.u.element);c.UD();return c},e5=function(a){if(!a.T){var b=new Hdb(a);
g.I(a,b);var c=new g.Jk(a);g.I(a,c);a.T=new Heb(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Xi)}return a.T},Veb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.AE();if(e){var f=g.zE();f&&g.gy(g.XO)(void 0,e,f,[g.wE(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Ueb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=L4(f.type,$eb),p=L4(f.style,afb),q=Xdb(f.data),t=0!==q.length?JSON.parse(q):{};var x=f.action;f=ceb;if(null==x)var z=null;else if(g.Oa(x)){l=[];for(var D=g.v(x),G=D.next();!G.done;G=D.next()){var O=f(G.value);
O&&l.push(O)}z=l}else{var N=f(x);z=N?[N]:[]}e=m&&n?new deb(m,n,p,z,t):null}else e=null}catch(r){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var K=Reb(f),W=null;switch(l.type){case "branding":if(f.player.V().qd)break;f.u.element.appendChild(K);W=new c5(K,e5(f),l);break;case "promotion":g.GS(f.player,K,4),W=new Ieb(K,e5(f),l)}W&&W.UD();if(f=W)g.I(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Zeb(a),g.I(a,a.j));if("card"===e.type){c=a.j;var Y=e&&e.data&&e.data.card_type;
f=e.data;if(Y)switch(l=f.tracking||{},l={JU:l.impression,click:l.click,close:l.close,gY:l.teaser_impression,pI:l.teaser_click},K=f.tracking_params||{},W=null,Y){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Mi:l,zo:K.card?g.wE(K.card):null,Yk:K.teaser?g.wE(K.teaser):null,Zf:K.icon?g.wE(K.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,cX:f.image_url,title:f.title,metaInfo:f.meta_info,url:N4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};W4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Mi:l,zo:K.card?g.wE(K.card):null,Yk:K.teaser?
g.wE(K.teaser):null,Zf:K.icon?g.wE(K.icon):null,gE:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:N4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};W4(c,e);break;case "productListing":f.signin_url&&(W=N4({target:"current",value:f.signin_url}));Y=[];for(var Q=f.offers||[],na=0;na<Q.length;na++)Y.push(new jeb(g.He(Q[na].merchant),g.He(Q[na].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Mi:l,zo:K.card?g.wE(K.card):null,Yk:K.teaser?g.wE(K.teaser):null,Zf:K.icon?g.wE(K.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,iB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:N4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),F8a:W,E8a:f.signin_title?f.signin_title:void 0,D8a:f.signin_message?f.signin_message:void 0,offers:Y,onClickCommand:null};W4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Mi:l,zo:K.card?g.wE(K.card):
null,Yk:K.teaser?g.wE(K.teaser):null,Zf:K.icon?g.wE(K.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,iB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:N4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};W4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Mi:l,zo:K.card?g.wE(K.card):null,Yk:K.teaser?g.wE(K.teaser):null,Zf:K.icon?g.wE(K.icon):null,gE:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:N4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},W4(c,e)}}else oeb(a.j,e);c=!0}}c&&
(w4(a.player),a.eH())},bfb=function(a,b){var c=!1;
a.j||(a.j=Zeb(a),g.I(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(peb(a.j,e.cardRenderer),c=!0);var f;!c||null!=(f=a.player.getVideoData())&&g.HM(f)||(c=a.j,d=b.headerText?g.bE(b.headerText):"",g.sf(c.Tb,d),c.T&&c.T.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.wE(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.wE(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Zf=b.icon.infoCardIconRenderer.trackingParams?g.wE(b.icon.infoCardIconRenderer.trackingParams):null,w4(a.player),a.eH())},cfb=function(a,b,c,d,e){if(!a.player.V().qd){var f=[];
b.navigationEndpoint&&g.S(b.navigationEndpoint,Z4)&&g.S(b.navigationEndpoint,Z4).browseId&&f.push(new $db("openUrl","click",new Ydb("/channel/"+g.S(b.navigationEndpoint,Z4).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.S(b.subscribeButton,
g.AM)){d.channel_id=g.S(b.subscribeButton,g.AM).channelId;var l;b=g.S(b.subscribeButton,g.AM);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.bE(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.bE(b.subscriberCountText))):(b.subscriberCountText&&(e=g.bE(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.bE(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.S(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.p3))?void 0:m.url)||"";l={subscribeText:g.bE(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.bE(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new deb(c,"branding","branding",f,d);l=Reb(a);a.u.element.appendChild(l);f=new c5(l,e5(a),f);f.UD();g.I(f,f);a.I[c]=f}},Web=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.isDisposed()||a.ea.push(g.up.wi(function(){b.apply(null,g.la(c))}))}},dfb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.tS.prototype.Qz=g.ba(18,function(a,b){var c=g.LT(this.wb());c&&c.Qz(a,b)});
var y4={},z4=null;g.Xa(B4,g.Wp);g.k=B4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Zc())return!1;A4(this);this.startTime=a=g.Va();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.ZG();this.El("play");-1==this.j&&this.El("resume");this.j=1;var b=g.Ra(this);b in y4||(y4[b]=this);Adb();Bdb(this,a);return!0};
g.k.stop=function(a){A4(this);this.j=0;a&&(this.progress=1);Cdb(this,this.progress);this.El("stop");this.Hq()};
g.k.pause=function(){this.Zc()&&(A4(this),this.j=-1,this.El("pause"))};
g.k.qa=function(){0==this.j||this.stop(!1);this.El("destroy");B4.Ff.qa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.hJ=function(){this.El("animate")};
g.k.El=function(a){this.dispatchEvent(new Ddb(a,this))};
g.Xa(Ddb,g.qb);g.Xa(C4,B4);C4.prototype.B=function(){};
C4.prototype.hJ=function(){this.B();C4.Ff.hJ.call(this)};
C4.prototype.Hq=function(){this.B();C4.Ff.Hq.call(this)};
C4.prototype.ZG=function(){this.B();C4.Ff.ZG.call(this)};
g.Xa(Edb,C4);Edb.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var Z4=new g.tr("browseEndpoint");g.w(Hdb,g.E);g.k=Hdb.prototype;g.k.Ra=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.yz(a,b,c);this.j.push(a);return a};
g.k.CG=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.Moa(a,b,c);this.j.push(a);return a};
g.k.Gc=function(a){g.zz(a);g.Ab(this.j,a)};
g.k.Df=function(){g.zz(this.j);this.j.length=0};
g.k.qa=function(){this.Df();g.E.prototype.qa.call(this)};g.w(Kdb,g.vT);g.k=Kdb.prototype;g.k.load=function(){g.vT.prototype.load.call(this);if(!F4(this)){var a=g.Xza(this.player.getVideoData());a?(a=Jdb(a,Ldb(this)),G4(this,a,!1)):Mdb(this)}};
g.k.unload=function(){G4(this,null);this.B&&(this.B.abort(),this.B=null);g.vT.prototype.unload.call(this)};
g.k.ph=function(a,b){return F4(this)?"loadCustomEndscreenRenderer"===a?(a=Jdb(b,"new"),G4(this,a),!0):null:null};
g.k.getOptions=function(){return F4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Db=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<efb.length;f++){var h=Math.abs(b.width-efb[f]);if(-1===e||d>=h)e=f,d=h}d=ffb[e];this.u&&g.Bm(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Lm(e.element,m,f);g.Hm(e.element,n,p);g.Np(e.element,gfb);256<m||256<f?g.Kp(e.element,"ytp-ce-large-round"):96<m||96<f?g.Kp(e.element,"ytp-ce-medium-round"):g.Kp(e.element,"ytp-ce-small-round");g.Np(e.element,hfb);m=h.left+h.width/2;h=h.top+l/2;g.Kp(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Np(e.element,ffb);g.Kp(e.element,d);(e=g.Se(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Bm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())K4(this,this.endscreen.impressionUrls),(a=g.AE())&&this.endscreen.visualElement&&g.dP(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.Kp(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Kp(b,"ytp-ce-shown");K4(this,c.impressionUrls);(b=g.AE())&&g.dP(b,c.visualElement);this.player.V().I&&this.player.Na("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Mp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Mp(b,"ytp-ce-shown");this.player.V().I&&this.player.Na("endscreenelementhidden",a)}};
g.k.t8=function(a){var b=this;a.target===window&&(new g.Cp(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Np(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var efb=[346,426,470,506,570,640,853,1280,1920],ffb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),hfb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],gfb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Zdb={cna:"current",uKa:"new"};var aeb={CLOSE:"close",SNa:"openUrl",SUBSCRIBE:"subscribe"},beb={Hla:"click",CLOSE:"close",Lwa:"hidden",ySa:"rollOut",zSa:"rollOver",VTa:"shown"};deb.prototype.Ye=function(){var a=eeb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var afb={sha:"anchored",mZ:"branding",CHANNEL:"channel",Sma:"cta",Owa:"highlightText",JAa:"label",PLAYLIST:"playlist",jQa:"popup",AWa:"speech",SUBSCRIBE:"subscribe",uZa:"title",VIDEO:"video",i4a:"website"},$eb={mZ:"branding",Gja:"card",Zoa:"drawer",Nwa:"highlight",AGa:"marker",vRa:"promotion",TEXT:"text",H5a:"widget"};g.w(R4,g.E);g.k=R4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.SD(a,b,{id:c,namespace:"annotations_module"});d&&this.Ya.set(a,d);e&&this.fb.set(a,e);this.context.F.ye([a])};
g.k.UD=function(){this.context.u.subscribe("resize",this.bF,this)};
g.k.ub=function(){return this.element};
g.k.iJ=function(a,b,c,d,e,f){if(this.sb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.pf(this.ub())};
g.k.bF=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=M4(a);if(f){var h=leb(f,a.target),l=function(){a.j&&e.context.F.pauseVideo();var m=e.context.videoData.D||!1,n=g.my(f||"");m&&n&&(n.v||n.list)?e.context.F.Kn(n.v,b,n.list,!1):g.DN(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);d5(this.context.logger,c,l,d);keb(f)||(c=g.AE(),d=b.itct,c&&d&&g.gP(c,g.wE(d)))}};
g.k.qa=function(){this.Ya.clear();this.fb.clear();g.E.prototype.qa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.w(neb,R4);g.k=neb.prototype;g.k.Hs=function(){this.oa&&W4(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.F.getRootNode())?(a=g.Mm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.bF=function(){var a=this.isAvailable();g.Nm(this.ub(),a);g.Op(this.context.F.getRootNode(),g.UW.IV_DRAWER_ENABLED,a);w4(this.F)};
g.k.destroy=function(){this.F.Qz(!1);try{this.F.getRootNode().removeChild(this.C)}catch(a){}g.kC(this.Z);g.Fz(this.Oa);this.Wa&&this.Wa.dispose();this.D&&this.D.dispose();R4.prototype.destroy.call(this)};
g.k.Q2=function(){if(this.B){d5(this.context.logger,a5(this).Mi.close);var a=g.AE();a&&this.J&&g.gP(a,this.J);V4(this)}};
g.k.l3=function(){g.Op(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.V4=function(){var a=g.AE(),b=a5(this);b=b?b.Zf:this.Zf;a&&b&&g.eP(a,[b])};
g.k.U4=function(){var a=g.AE(),b=a5(this);b=b?b.Zf:this.Zf;a&&b&&g.fP(a,[b])};
g.k.RZ=function(){var a=a5(this);d5(this.context.logger,a.Mi.gY);var b=g.AE();b&&a&&g.eP(b,[a.Yk,a.Zf])};
g.k.W4=function(){var a=g.AE(),b=a5(this);a&&b&&g.fP(a,[b.Yk])};
g.k.QZ=function(a){var b=a5(this),c=g.AE();this.j?a?(a=this.context.logger,d5(a,b.Mi.pI),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Yk&&g.gP(c,b.Yk)):(a=this.context.logger,d5(a,b.Mi.pI),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Zf&&g.gP(c,b.Zf)):(a=this.context.logger,d5(a,b.Mi.pI),a.F.sendVideoStatsEngageEvent(4,void 0),c&&this.Zf&&g.gP(c,this.Zf))};g.w(b5,R4);b5.prototype.UD=function(){R4.prototype.UD.call(this);Ceb(this)};
b5.prototype.show=function(){R4.prototype.show.call(this);var a=g.AE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.eP(a,[g.wE(b.itct)])};
b5.prototype.hide=function(){R4.prototype.hide.call(this);var a=g.AE(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.fP(a,[g.wE(b.itct)])};g.w(c5,b5);
c5.prototype.show=function(){if(!this.isActive){b5.prototype.show.call(this);if(!this.J){g.Kp(this.ub(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ia:["branding-img","iv-click-target"],X:{"aria-label":"Filigrana del canale",src:a.image_url,width:a.image_width,height:a.image_height}});g.Nm(this.u,!1);var b=this.createElement({G:"button",Ia:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.ub().appendChild(b);var c=this.annotation.Ye();c&&S4(this,
b,c,this.annotation.id,a.session_data);Geb(this,a);this.J=!0}g.Nm(this.ub(),!0);this.isActive=!0;this.u&&(Deb(this,this.u),g.Kp(this.context.F.getRootNode(),"ytp-branding-shown"))}};
c5.prototype.hide=function(){this.isActive&&(b5.prototype.hide.call(this),g.Nm(this.ub(),!1),this.isActive=!1,g.Mp(this.context.F.getRootNode(),"ytp-branding-shown"))};
c5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);b5.prototype.destroy.call(this)};g.w(Ieb,b5);g.k=Ieb.prototype;g.k.show=function(){this.isActive||(b5.prototype.show.call(this),this.ea||(Keb(this),this.ea=!0),g.Nm(this.ub(),!0),g.Qf(function(){g.Mp(this.ub(),"iv-promo-inactive")},100,this),this.ub().removeAttribute("aria-hidden"),this.isActive=!0,Oeb(this),Leb(this),Meb(this,this.I))};
g.k.hide=function(){this.isActive&&(g.Kp(this.ub(),"iv-promo-inactive"),this.isActive=!1,this.ub().setAttribute("aria-hidden","true"))};
g.k.iJ=function(a,b,c,d,e,f){return this.isCollapsed?!1:b5.prototype.iJ.call(this,a,b,c,d,e,f)};
g.k.e4=function(a){this.T=!0;Jeb(this,500,a)};
g.k.d4=function(){this.T=!1;Neb(this)};
g.k.X3=function(a){a.stopPropagation();this.hide()};
g.k.Y3=function(a){a.stopPropagation();Oeb(this);this.isCollapsed=!0;g.Kp(this.ub(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();b5.prototype.destroy.call(this)};g.w(Qeb,g.vT);g.k=Qeb.prototype;g.k.ph=function(a,b){if(!dfb(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.R8a(b))&&Veb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(reb(this.j,b),w4(this.player)),!0}return null};
g.k.getOptions=function(){return dfb(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.lw=function(){var a=this.player.V(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.D&&a.Z||g.nS(this.player.app)?!1:1===c&&!b.ZR||a.Aa.get(b.videoId)||g.IM(b)||g.JM(b)?!0:!1};
g.k.eH=function(){if(this.B){var a=this.player.jb().getVideoContentRect(!0);g.Lm(this.B.element,a.width,a.height);g.Hm(this.B.element,a.left,a.top)}if(this.j){var b=this.player.zk();a=this.j;b=b.width;g.Op(a.C,"iv-drawer-small",426>=b);g.Op(a.C,"iv-drawer-big",1280<=b)}};
g.k.SZ=function(a){Seb(this,a.state);g.MN(a.state,2)&&(this.nk()&&this.xo()&&2!==this.player.getPresentingPlayerType()&&this.Rz(!1),this.Qz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.uy(h)&&h.responseXML?h.responseXML:null)&&(Veb(b,h),g.Kp(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.vT.prototype.load.call(this);Seb(this,this.player.Cb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.dA()&&(a=Web(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().Aa.get(d);f&&Xeb(e,f);f=f&&(f.NK||f.kB);if(!c.Kw||f)c.Wa?Teb(this,c.Wa,e):(this.zw=function(){if(!b.J)b.onVideoDataChange(e);var h=b.player.getVideoData();if((null==h?0:g.HM(h))&&!b.Z){var l,m;if(h=null==(l=h.hd)?void 0:null==(m=l.cards)?void 0:m.cardCollectionRenderer)bfb(b,h),b.Z=!0}},this.player.addEventListener("videodatachange",this.zw));
g.GS(this.player,this.B.element,4);this.eH();(f=g.IM(c))&&bfb(this,f);(f=g.JM(c))&&f.featuredChannel&&cfb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Wa&&Teb(this,b.Wa,a)};
g.k.unload=function(){this.player.gf("annotations_module");for(var a=g.v(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.T=null;this.j&&(this.j.destroy(),this.j=null,w4(this.player));this.J=!1;this.D&&(this.D.abort(),this.D=null);this.Z=!1;this.I={};this.u.hide();g.vT.prototype.unload.call(this);this.B.detach();this.zw&&(this.player.removeEventListener("videodatachange",this.zw),this.zw=null)};
g.k.KW=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Yeb(this):this.load())};
g.k.nk=function(){return!!this.j&&this.j.isAvailable()};
g.k.xo=function(){return!!this.j&&this.j.B};
g.k.Rz=function(a,b,c){b=void 0===b?!1:b;this.nk();this.j&&(a?c?U4(this.j,c,b):U4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):V4(this.j))};
g.k.Qz=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.qa=function(){this.player.V().Aa.unsubscribe("vast_info_card_add",this.KW,this);g.Mp(this.player.getRootNode(),g.UW.IV_DRAWER_OPEN);for(var a=this.ea,b=g.up,c=0,d=a.length;c<d;c++)b.Em(a[c]);this.ea.length=0;g.vT.prototype.qa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.uT("annotations_module",Qeb);g.uT("creatorendscreen",Kdb);})(_yt_player);
