(function(g){var window=this;'use strict';var ohb=function(a,b){a.Na("onAutonavCoundownStarted",b)},a6=function(a,b,c){g.Op(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.vg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.BL&&(b.lengthText?(e=b.lengthText||null,f=b.yv||null):b.lengthSeconds&&(e=g.aR(b.lengthSeconds),f=g.aR(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.zL(d).type;var l=b instanceof g.BL?b.isLivePlayback:null,m=b instanceof g.BL?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,t=[],x=[];n&&t.push(n);p&&(t.push(p),x.push(p));q&&x.push(q);c={title:b.title,author:n,author_and_views:t.join(" \u2022 "),aria_label:b.ariaLabel||
g.hO("Guarda $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Ak(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:x.join(" \u2022 "),autoplayAlternativeHeader:b.Gr};b instanceof g.AL&&(c.playlist_length=b.playlistLength);a.update(c)},b6=function(a){var b=a.V(),c=b.C;
g.V.call(this,{G:"a",N:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.ea:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",Ia:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{G:"div",X:{"aria-label":"{{timestamp}}"},Ia:["ytp-autonav-timestamp"],ra:"{{duration}}"},{G:"div",Ia:["ytp-autonav-live-stamp"],ra:"Dal vivo"},
{G:"div",Ia:["ytp-autonav-upcoming-stamp"],ra:"In programma"},{G:"div",N:"ytp-autonav-list-overlay",W:[{G:"div",N:"ytp-autonav-mix-text",ra:"Mix"},{G:"div",N:"ytp-autonav-mix-icon"}]}]},{G:"div",Ia:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ra:"{{title}}"},{G:"div",Ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ra:"{{author}}"},{G:"div",Ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ra:"{{views_and_publish_time}}"}]});this.F=
a;this.suggestion=null;this.j=c;this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress)},c6=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{G:"div",N:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.D=void 0;this.B=0;this.container=new g.V({G:"div",N:"ytp-autonav-endscreen-countdown-container"});g.I(this,this.container);this.container.Ea(this.element);b=a.V();var d=b.C;this.F=a;this.suggestion=null;this.onVideoDataChange("newdata",this.F.getVideoData());this.S(a,"videodatachange",this.onVideoDataChange);this.j=new g.V({G:"div",N:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",N:"ytp-autonav-endscreen-upnext-header"},{G:"div",N:"ytp-autonav-endscreen-upnext-alternative-header",ra:"{{autoplayAlternativeHeader}}"},{G:"a",N:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.ea:""},W:[{G:"div",N:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},W:[{G:"div",X:{"aria-label":"{{timestamp}}"},Ia:["ytp-autonav-timestamp"],
ra:"{{duration}}"},{G:"div",Ia:["ytp-autonav-live-stamp"],ra:"Dal vivo"},{G:"div",Ia:["ytp-autonav-upcoming-stamp"],ra:"In programma"}]},{G:"div",N:"ytp-autonav-endscreen-video-info",W:[{G:"div",N:"ytp-autonav-endscreen-premium-badge"},{G:"div",N:"ytp-autonav-endscreen-upnext-title",ra:"{{title}}"},{G:"div",N:"ytp-autonav-endscreen-upnext-author",ra:"{{author}}"},{G:"div",N:"ytp-autonav-view-and-date",ra:"{{views_and_publish_time}}"},{G:"div",N:"ytp-autonav-author-and-view",ra:"{{author_and_views}}"}]}]}]});
g.I(this,this.j);this.j.Ea(this.container.element);d||this.S(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.HQ);this.F.tb(this.container.element,this,115127);this.F.tb(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({G:"div",N:"ytp-autonav-overlay"});g.I(this,this.overlay);this.overlay.Ea(this.container.element);this.u=new g.V({G:"div",N:"ytp-autonav-endscreen-button-container"});g.I(this,this.u);this.u.Ea(this.container.element);this.cancelButton=
new g.V({G:"button",Ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Annulla riproduzione automatica"},ra:"Annulla"});g.I(this,this.cancelButton);this.cancelButton.Ea(this.u.element);this.cancelButton.Ra("click",this.ZZ,this);this.F.tb(this.cancelButton.element,this,115129);this.playButton=new g.V({G:"a",Ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Riproduci il prossimo video"},ra:"Riproduci ora"});g.I(this,this.playButton);this.playButton.Ea(this.u.element);this.playButton.Ra("click",this.HQ,this);this.F.tb(this.playButton.element,this,115130);this.C=new g.Cp(function(){phb(c)},500);
g.I(this,this.C);this.GQ();this.S(a,"autonavvisibility",this.GQ);this.F.K("web_autonav_color_transition")&&(this.S(a,"autonavchange",this.YZ),this.S(a,"onAutonavCoundownStarted",this.X5))},d6=function(a){var b=a.F.zk(!0,a.F.isFullscreen());
g.Op(a.container.element,"ytp-autonav-endscreen-small-mode",a.Vg(b));g.Op(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.kI);g.Op(a.F.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.F.zf());g.Op(a.F.getRootNode(),"countdown-running",a.Fk());g.Op(a.container.element,"ytp-player-content",a.F.zf());g.Bm(a.overlay.element,{width:b.width+"px"});if(!a.Fk()){a.F.zf()?qhb(a,Math.round(rhb(a)/1E3)):qhb(a);b=!!a.suggestion&&!!a.suggestion.Gr;var c=a.F.zf()||!b;
g.Op(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Op(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.YP(a.u,a.F.zf());g.Op(a.element,"ytp-enable-w2w-color-transitions",shb(a))}},phb=function(a){var b=rhb(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);qhb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Fk()?a.select(!0):a.Fk()&&a.C.start()},rhb=function(a){if(a.F.isFullscreen()){var b;
a=null==(b=a.F.getVideoData())?void 0:b.RI;return-1===a||void 0===a?8E3:a}return 0<=a.F.Zr()?a.F.Zr():g.bJ(a.F.V().experiments,"autoplay_time")||1E4},shb=function(a){var b;
return!(null==(b=a.F.getVideoData())||!b.watchToWatchTransitionRenderer)},qhb=function(a,b){b=void 0===b?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.nf(a);if(0<=b){b=String(b);var c="Prossimo video tra $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Prossimo video tra $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.lf("Prossimo video tra $SECONDS".slice(0,d)));var e=g.$e("span");g.Ip(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.sf(e,b);a.appendChild(e);a.appendChild(g.lf("Prossimo video tra $SECONDS".slice(d+c.length)));return}}g.sf(a,"Prossimo video")},e6=function(a,b){g.V.call(this,
{G:"div",
Ia:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},f6=function(a){g.V.call(this,{G:"div",
Ia:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{G:"div",N:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{G:"span",N:"ytp-upnext-top",W:[{G:"span",N:"ytp-upnext-header",ra:"Prossimo video"},{G:"span",N:"ytp-upnext-title",ra:"{{title}}"},{G:"span",N:"ytp-upnext-author",ra:"{{author}}"}]},{G:"a",N:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Riproduci il prossimo video"},W:[{G:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},W:[{G:"circle",N:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",N:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",N:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",N:"ytp-upnext-bottom",W:[{G:"span",N:"ytp-upnext-cancel"},{G:"span",N:"ytp-upnext-paused",
ra:"Riproduzione automatica in pausa"}]}]});this.api=a;this.cancelButton=null;this.D=this.Da("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.Cp(this.lF,5E3,this);this.u=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=new g.V({G:"button",Ia:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Annulla riproduzione automatica"},ra:"Annulla"});g.I(this,this.cancelButton);this.cancelButton.Ra("click",this.a_,this);this.cancelButton.Ea(b);
this.cancelButton&&this.api.tb(this.cancelButton.element,this,115129);g.I(this,this.C);this.api.tb(this.element,this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.S(b,"click",this.b_);this.api.tb(b,this,115130);this.IQ();this.S(a,"autonavvisibility",this.IQ);this.S(a,"mdxnowautoplaying",this.K6);this.S(a,"mdxautoplaycanceled",this.L6);g.Op(this.element,"ytp-upnext-mobile",this.api.V().u)},thb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.RI;return-1===a||void 0===a?8E3:a}return 0<=a.api.Zr()?a.api.Zr():g.bJ(a.api.V().experiments,"autoplay_time")||1E4},uhb=function(a,b){b=thb(a,b);
var c=Math,d=c.min;var e=(0,g.EA)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Fk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Fk()&&a.j.start()},g6=function(a){e6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({G:"div",N:"ytp-suggestion-panel",W:[{G:"div",Ia:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ra:"Altri video"}]});this.J=new g.V({G:"div",N:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new c6(this.player);g.I(this,this.u);this.u.Ea(this.element);a.getVideoData().Hf?this.j=this.u:(this.j=new f6(a),g.GS(this.player,this.j.element,4),g.I(this,this.j));this.overlay=new g.V({G:"div",
N:"ytp-autonav-overlay-cancelled-state"});g.I(this,this.overlay);this.overlay.Ea(this.element);this.C=new g.NH(this);g.I(this,this.C);g.I(this,this.table);this.table.Ea(this.element);this.table.show();g.I(this,this.J);this.J.Ea(this.table.element);this.hide()},h6=function(a){var b=a.zf();
b!==a.D&&(a.D=b,a.player.ma("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},i6=function(a,b){g.V.call(this,{G:"button",
Ia:["ytp-watch-on-youtube-button","ytp-button"],ra:"{{content}}"});this.F=a;this.buttonType=this.buttonType=b;b=this.F.getVideoData();if(a.K("embeds_enable_server_driven_watch_again_on_youtube")){var c,d;if(c=(a=null==(c=b.hd)?void 0:null==(d=c.playerOverlays)?void 0:d.playerOverlayRenderer)&&g.S(a.watchOnYoutubeButton,g.KKa))this.j=c}if(this.j)this.update({content:this.j.title}),this.F.Yf(this.element,this),this.F.jg(this.element,this.j.trackingParams||null);else{switch(this.buttonType){case 1:c=
"Guarda di nuovo su YouTube";d=156915;break;case 2:c="Continua a guardare su YouTube";d=156942;break;default:c="Continua a guardare su YouTube",d=156942}this.update({content:c});this.F.tb(this.element,this,d)}2===this.buttonType&&g.Kp(this.element,"ytp-continue-watching-button");this.Ra("click",this.onClick);g.YP(this,!0)},j6=function(a,b){e6.call(this,a,"embeds-lite-endscreen");
this.F=a;this.j=b;this.F.tb(this.element,this,156943);this.watchButton=new i6(a,2);g.I(this,this.watchButton);this.watchButton.Ea(this.element);this.hide()},vhb=function(a){e6.call(this,a,"subscribecard-endscreen");
this.j=new g.V({G:"div",N:"ytp-subscribe-card",W:[{G:"img",N:"ytp-author-image",X:{src:"{{profilePicture}}"}},{G:"div",N:"ytp-subscribe-card-right",W:[{G:"div",N:"ytp-author-name",ra:"{{author}}"},{G:"div",N:"html5-subscribe-button-container"}]}]});g.I(this,this.j);this.j.Ea(this.element);var b=a.getVideoData();this.subscribeButton=new g.jU("Iscriviti",null,"Annulla iscrizione",null,!0,!1,b.bk,b.subscribed,"trailer-endscreen",null,a);g.I(this,this.subscribeButton);this.subscribeButton.Ea(this.j.Da("html5-subscribe-button-container"));
this.S(a,"videodatachange",this.Qa);this.Qa();this.hide()},k6=function(a){var b=a.V(),c=g.QH||g.ZJ?{style:"will-change: opacity"}:void 0,d=b.C,e=["ytp-videowall-still"];
b.u&&e.push("ytp-videowall-show-text");g.V.call(this,{G:"a",Ia:e,X:{href:"{{url}}",target:d?b.ea:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{G:"div",N:"ytp-videowall-still-image",X:{style:"{{background}}"}},{G:"span",N:"ytp-videowall-still-info",X:{"aria-hidden":"true"},W:[{G:"span",N:"ytp-videowall-still-info-bg",W:[{G:"span",N:"ytp-videowall-still-info-content",X:c,W:[{G:"span",N:"ytp-videowall-still-info-title",ra:"{{title}}"},
{G:"span",N:"ytp-videowall-still-info-author",ra:"{{author_and_views}}"},{G:"span",N:"ytp-videowall-still-info-live",ra:"Dal vivo"},{G:"span",N:"ytp-videowall-still-info-duration",ra:"{{duration}}"}]}]}]},{G:"span",Ia:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{G:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",N:"ytp-videowall-still-listlabel-length",W:[" (",{G:"span",ra:"{{playlist_length}}"},")"]}]},{G:"span",Ia:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{G:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",N:"ytp-videowall-still-listlabel-length",ra:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.NH(this);g.I(this,this.j);this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress);this.j.S(a,"videodatachange",this.onVideoDataChange);a.Yf(this.element,this);this.onVideoDataChange()},l6=function(a){e6.call(this,a,"videowall-endscreen");
var b=this;this.F=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.T=null;this.u=new g.NH(this);g.I(this,this.u);this.I=new g.Cp(function(){g.Kp(b.element,"ytp-show-tiles")},0);
g.I(this,this.I);var c=new g.V({G:"button",Ia:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Indietro"},W:[g.dQ()]});g.I(this,c);c.Ea(this.element);c.Ra("click",this.f_,this);this.table=new g.VP({G:"div",N:"ytp-endscreen-content"});g.I(this,this.table);this.table.Ea(this.element);c=new g.V({G:"button",Ia:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Avanti"},W:[g.eQ()]});g.I(this,c);c.Ea(this.element);c.Ra("click",this.e_,this);a.getVideoData().Hf?this.j=new c6(a,!0):this.j=new f6(a);
g.I(this,this.j);g.GS(this.player,this.j.element,4);a.tb(this.element,this,158789);this.hide()},m6=function(a){return g.HS(a.player)&&a.eB()&&!a.C},n6=function(a){var b=a.zf();
b!==a.J&&(a.J=b,a.player.ma("autonavvisibility"))},o6=function(a){e6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new i6(a,1);g.I(this,this.watchButton);this.watchButton.Ea(this.element);g.S8a(a)&&(this.j=new g.Z2(a,g.kS(a)),g.I(this,this.j),this.u=new g.V({G:"div",Ia:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},W:[this.j]}),g.I(this,this.u),this.j.Ea(this.u.element),this.u.Ea(this.element));a.tb(this.element,this,156914);this.hide()},zhb=function(a){g.vT.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.NH(this);g.I(this,this.listeners);var c=a.V(),d=a.getVideoData();d=d&&0!==d.endSeconds;if(g.kz(g.rK(c))&&d&&!g.DS(a))this.u=!0,this.endScreen=new j6(a,g.kS(a));else{var e;(c.K("shorts_mode_to_player_api")?a.Ub():null==(e=g.kS(a))?0:e.Ub())?this.endScreen=new o6(a):whb(a)?(this.C=!0,xhb(this),this.j?this.endScreen=new g6(a):this.endScreen=new l6(a)):c.Vf?this.endScreen=new vhb(a):this.endScreen=new e6(a)}g.I(this,this.endScreen);
g.GS(a,this.endScreen.element,4);yhb(this);this.listeners.S(a,"videodatachange",this.onVideoDataChange,this);this.listeners.S(a,g.UD("endscreen"),function(f){b.onCueRangeEnter(f)});
this.listeners.S(a,g.VD("endscreen"),function(f){b.onCueRangeExit(f)})},xhb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.il&&a.B===b.Hf)return!1;a.j=b.il;a.B=b.Hf;return!0},whb=function(a){a=a.V();
return a.Vc&&!a.Vf},yhb=function(a){a.player.gf("endscreen");
var b=a.player.getVideoData();b=new g.SD(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.SD(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.ye([b,c])};
g.WV.prototype.Tz=g.ba(36,function(a){this.oO!==a&&(this.oO=a,this.dl())});
g.MU.prototype.Uq=g.ba(35,function(a){this.u!==a&&(this.u=a,this.Qa())});
g.WV.prototype.Uq=g.ba(34,function(a){this.shareButton&&this.shareButton.Uq(a)});
g.IU.prototype.Tq=g.ba(33,function(a){this.u!==a&&(this.u=a,this.Qa())});
g.WV.prototype.Tq=g.ba(32,function(a){this.overflowButton&&this.overflowButton.Tq(a)});
g.aU.prototype.TD=g.ba(31,function(a){this.pO!==a&&(this.pO=a,this.wp())});
g.tS.prototype.Zr=g.ba(5,function(){return this.app.Zr()});
g.zZ.prototype.Zr=g.ba(4,function(){return this.getVideoData().aS});g.w(b6,g.V);b6.prototype.select=function(){this.F.Kn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.AB||void 0)&&this.F.qb(this.element)};
b6.prototype.onClick=function(a){g.QT(a,this.F,this.j,this.suggestion.sessionData||void 0)&&this.select()};
b6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.zO(a)||(this.select(),g.AO(a))}};g.w(c6,g.V);g.k=c6.prototype;g.k.DE=function(a){this.suggestion!==a&&(this.suggestion=a,a6(this.j,a),this.playButton.updateValue("url",this.suggestion.Ak()),d6(this))};
g.k.Fk=function(){return 0<this.B};
g.k.bA=function(){this.Fk()||(this.B=Date.now(),phb(this),ohb(this.F,rhb(this)),g.Op(this.F.getRootNode(),"countdown-running",this.Fk()))};
g.k.Ov=function(){this.Zq();phb(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.sf(a,"Prossimo video")};
g.k.Zq=function(){this.Fk()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.F.nextVideo(!1,void 0===a?!1:a);this.Zq()};
g.k.HQ=function(a){g.QT(a,this.F)&&(a.currentTarget===this.playButton.element?this.F.qb(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.F.Ua(a,!0),this.F.qb(a)),this.select())};
g.k.ZZ=function(){this.F.qb(this.cancelButton.element);g.xS(this.F,!0);this.D&&this.F.Na("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.J1)?void 0:c.command};
g.k.X5=function(a){if(shb(this)){var b=this.F.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.jR(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.jR(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.jR(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.jR(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.jR(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.jR(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Op(this.element,"ytp-w2w-animate",!0)}};
g.k.YZ=function(a){this.F.K("web_autonav_color_transition")&&2!==a&&g.Op(this.element,"ytp-w2w-animate",!1)};
g.k.GQ=function(){var a=this.F.zf();this.I&&this.yb!==a&&g.YP(this,a);d6(this);this.F.Ua(this.container.element,a);this.F.Ua(this.cancelButton.element,a);this.F.Ua(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.F.Ua(this.playButton.element,a)};
g.k.Vg=function(a){return 400>a.width||459>a.height};g.w(e6,g.V);g.k=e6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.eB=function(){return!1};
g.k.zf=function(){return!1};
g.k.cV=function(){return!1};g.w(f6,g.V);g.k=f6.prototype;g.k.lF=function(){this.notification&&(this.C.stop(),this.Gc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.DE=function(a){this.suggestion=a;a6(this,a,"hqdefault.jpg")};
g.k.IQ=function(){g.YP(this,this.api.zf());this.api.Ua(this.element,this.api.zf());this.api.Ua(this.Da("ytp-upnext-autoplay-icon"),this.api.zf());this.cancelButton&&this.api.Ua(this.cancelButton.element,this.api.zf())};
g.k.T6=function(){window.focus();this.lF()};
g.k.bA=function(a){var b=this;this.Fk()||(g.lC("a11y-announce","Prossimo video "+this.suggestion.title),this.u=(0,g.EA)(),this.j=new g.Cp(function(){uhb(b,a)},25),uhb(this,a),ohb(this.api,thb(this,a)));
g.Mp(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Fk=function(){return!!this.j};
g.k.Ov=function(){this.Zq();this.u=(0,g.EA)();uhb(this);g.Kp(this.element,"ytp-upnext-autoplay-paused")};
g.k.Zq=function(){this.Fk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.lF(),this.notification=new Notification("Prossimo video",{body:this.suggestion.title,icon:this.suggestion.vg()}),this.B=this.S(this.notification,"click",this.T6),this.C.start())}this.Zq();this.api.nextVideo(!1,a)};
g.k.b_=function(a){!g.rf(this.cancelButton.element,g.xO(a))&&g.QT(a,this.api)&&(this.api.zf()&&this.api.qb(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.a_=function(){this.api.zf()&&this.cancelButton&&this.api.qb(this.cancelButton.element);g.xS(this.api,!0)};
g.k.K6=function(a){this.api.getPresentingPlayerType();this.show();this.bA(a)};
g.k.L6=function(){this.api.getPresentingPlayerType();this.Zq();this.hide()};
g.k.qa=function(){this.Zq();this.lF();g.V.prototype.qa.call(this)};g.w(g6,e6);g.k=g6.prototype;g.k.create=function(){e6.prototype.create.call(this);this.C.S(this.player,"appresize",this.FA);this.C.S(this.player,"onVideoAreaChange",this.FA);this.C.S(this.player,"videodatachange",this.onVideoDataChange);this.C.S(this.player,"autonavchange",this.JQ);this.C.S(this.player,"autonavcancel",this.c_);this.onVideoDataChange()};
g.k.show=function(){e6.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.xS(this.player,!1);g.HS(this.player)&&this.eB()&&!this.B?(h6(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.bA():3===this.videoData.autonavState&&this.j.Ov()):(g.xS(this.player,!0),h6(this));this.FA()};
g.k.hide=function(){e6.prototype.hide.call(this);this.j.Ov();h6(this)};
g.k.FA=function(){var a=this.player.zk(!0,this.player.isFullscreen());h6(this);d6(this.u);g.Op(this.element,"ytp-autonav-cancelled-small-mode",this.Vg(a));g.Op(this.element,"ytp-autonav-cancelled-tiny-mode",this.xG(a));g.Op(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Bm(this.overlay.element,{width:a.width+"px"});if(!this.D)for(a=0;a<this.videos.length;a++)g.Op(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.K("web_player_autonav_empty_suggestions_fix")){var b=g.lM(this.videoData);b&&(this.j.DE(b),this.j!==this.u&&this.u.DE(b))}if(a&&a.length)for(b=0;b<Ahb.length;++b){var c=Ahb[b];if(a&&a[c]){this.videos[b]=new b6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,a6(d,c));g.I(this,this.videos[b]);this.videos[b].Ea(this.J.element)}}this.FA()}};
g.k.JQ=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Zq(),this.yb&&this.FA()):(this.I=!0,this.zf()&&(2===a?this.j.bA():3===a&&this.j.Ov()))};
g.k.c_=function(a){a?this.JQ(1):(this.B=null,this.I=!1)};
g.k.eB=function(){return 1!==this.videoData.autonavState};
g.k.Vg=function(a){return(910>a.width||459>a.height)&&!this.xG(a)&&!(400>=a.width||360>=a.height)};
g.k.xG=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.zf=function(){return this.yb&&g.HS(this.player)&&this.eB()&&!this.B};
var Ahb=[1,3,2,4];g.w(i6,g.V);g.k=i6.prototype;g.k.onClick=function(a){this.F.K("web_player_log_click_before_generating_ve_conversion_params")&&this.F.qb(this.element);this.j?this.F.Na("innertubeCommand",g.S(this.j.onTap,g.$S)):g.RT(this.getVideoUrl(),this.F,a);this.F.K("web_player_log_click_before_generating_ve_conversion_params")||this.F.qb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.F.getVideoUrl(a,!1,!1,!0);var b=this.F.V();if(g.aK(b)||g.jK(b)){var c={};b.ya&&g.aK(b)&&g.bS(c,b.loaderUrl);g.aK(b)&&g.iS(this.F,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.aS(c,b);a=g.Ui(a,c)}return a};
g.k.Ua=function(){this.F.Ua(this.element,this.yb&&this.ea)};
g.k.show=function(){g.V.prototype.show.call(this);this.Ua()};
g.k.hide=function(){g.V.prototype.hide.call(this);this.Ua()};
g.k.Zb=function(a){g.V.prototype.Zb.call(this,a);this.Ua()};g.w(j6,e6);j6.prototype.show=function(){3!==this.player.getPlayerState()&&(e6.prototype.show.call(this),this.j.Tz(!0),this.j.Uq(!0),this.F.V().hm||this.j.Tq(!0),this.F.Ua(this.element,!0),this.watchButton.Zb(!0))};
j6.prototype.hide=function(){e6.prototype.hide.call(this);this.j.Tz(!1);this.j.Uq(!1);this.j.Tq(!1);this.F.Ua(this.element,!1);this.watchButton.Zb(!1)};g.w(vhb,e6);vhb.prototype.Qa=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.bk;var b=this.subscribeButton;a.subscribed?b.j():b.u()};g.w(k6,g.V);k6.prototype.select=function(){this.api.Kn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.AB||void 0)&&this.api.qb(this.element)};
k6.prototype.onClick=function(a){if(g.aK(this.api.V())&&this.api.K("web_player_log_click_before_generating_ve_conversion_params")){this.api.qb(this.element);var b=this.suggestion.Ak(),c={};g.rKa(this.api,c,"emb_rel_end");b=g.Ui(b,c);g.RT(b,this.api,a)}else g.QT(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
k6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.zO(a)||(this.select(),g.AO(a))}};
k6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.C};g.w(l6,e6);g.k=l6.prototype;g.k.create=function(){e6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Dp();this.u.S(this.player,"appresize",this.Dp);this.u.S(this.player,"onVideoAreaChange",this.Dp);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.u.S(this.player,"autonavchange",this.kJ);this.u.S(this.player,"autonavcancel",this.d_);a=this.videoData.autonavState;a!==this.T&&this.kJ(a);this.u.S(this.element,"transitionend",this.h8)};
g.k.destroy=function(){g.Fz(this.u);g.kb(this.stills);this.stills=[];e6.prototype.destroy.call(this);g.Mp(this.element,"ytp-show-tiles");this.I.stop();this.T=this.videoData.autonavState};
g.k.eB=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.yb;e6.prototype.show.call(this);g.Mp(this.element,"ytp-show-tiles");this.player.V().u?g.Ep(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.xS(this.player,!1);m6(this)?(n6(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.bA():3===this.videoData.autonavState&&this.j.Ov()):(g.xS(this.player,!0),n6(this));a!==this.yb&&this.player.Ua(this.element,
!0)};
g.k.hide=function(){var a=this.yb;e6.prototype.hide.call(this);this.j.Ov();n6(this);a!==this.yb&&this.player.Ua(this.element,!1)};
g.k.h8=function(a){g.xO(a)===this.element&&this.Dp()};
g.k.Dp=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.lM(d)];if(e.length){g.Kp(this.element,"ytp-endscreen-paginate");var f=this.F.zk(!0,this.F.isFullscreen());if(a=g.kS(this.F))a=a.xg()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,t=b/2,x=a<=l-2&&p>=t*n,z=b<=m-2&&p>=q*n;if((q+1)/t*d/h>h/(q/(t+1)*d)&&z)p-=q*n,b+=2;else if(x)p-=t*n,a+=2;else if(z)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Lm(f,n,p);g.Bm(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.DE(g.lM(this.videoData));this.j instanceof
c6&&d6(this.j);g.Op(this.element,"ytp-endscreen-takeover",m6(this));n6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,x=0,d&&l>=a-2&&m>=b-2?x=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(x=2):x=2),q=g.ue(q+this.B,c),0!==x){t=this.stills[h];t||(t=new k6(this.player),this.stills[h]=t,f.appendChild(t.element));z=Math.floor(p*m/b);var D=Math.floor(n*l/a),G=Math.floor(p*(m+x)/b)-z-4,O=Math.floor(n*(l+x)/a)-D-4;g.Hm(t.element,D,z);g.Lm(t.element,O,G);g.Bm(t.element,"transitionDelay",
(m+l)/20+"s");g.Op(t.element,"ytp-videowall-still-mini",1===x);g.Op(t.element,"ytp-videowall-still-large",2<x);x=Math.max(O,G);g.Op(t.element,"ytp-videowall-still-round-large",256<=x);g.Op(t.element,"ytp-videowall-still-round-medium",96<x&&256>x);g.Op(t.element,"ytp-videowall-still-round-small",96>=x);q=e[q];t.suggestion!==q&&(t.suggestion=q,x=t.api.V(),z=g.Jp(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",a6(t,q,z),g.aK(x)&&!t.api.K("web_player_log_click_before_generating_ve_conversion_params")&&
(z=q.Ak(),D={},x.ya&&g.bS(D,x.loaderUrl),g.iS(t.api,"addEmbedsConversionTrackingParams",[D]),z=g.Ui(z,g.aS(D,"emb_rel_end")),t.updateValue("url",z)),(q=(q=q.sessionData)&&q.itct)&&t.api.jg(t.element,q));h++}f.ariaBusy="false";g.Op(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.pf(a.element),g.jb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Dp())};
g.k.e_=function(){this.B+=this.stills.length;this.Dp()};
g.k.f_=function(){this.B-=this.stills.length;this.Dp()};
g.k.cV=function(){return this.j.Fk()};
g.k.kJ=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Zq(),this.yb&&this.Dp()):(this.D=!0,this.yb&&m6(this)&&(2===a?this.j.bA():3===a&&this.j.Ov()))};
g.k.d_=function(a){if(a){for(a=0;a<this.stills.length;a++)this.F.Ua(this.stills[a].element,!0);this.kJ(1)}else this.C=null,this.D=!1;this.Dp()};
g.k.zf=function(){return this.yb&&m6(this)};g.w(o6,e6);o6.prototype.show=function(){if(3!==this.player.getPlayerState()){e6.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.Op(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.kS(this.player))||c.TD(!0);this.player.Ua(this.element,!0);this.watchButton.Zb(!0)}};
o6.prototype.hide=function(){e6.prototype.hide.call(this);var a;null==(a=g.kS(this.player))||a.TD(!1);this.player.Ua(this.element,!1);this.watchButton.Zb(!1)};g.w(zhb,g.vT);g.k=zhb.prototype;g.k.lw=function(){var a;if((this.player.V().K("shorts_mode_to_player_api")?this.player.Ub():null==(a=g.kS(this.player))?0:a.Ub())||this.u)return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.lM(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!whb(this.player)||c;c=a.ij||g.jK(a.B);var d=this.player.LB();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.zf=function(){return this.endScreen.zf()};
g.k.I4=function(){return this.zf()?this.endScreen.cV():!1};
g.k.qa=function(){this.player.gf("endscreen");g.vT.prototype.qa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.wb().cf.get("heartbeat"),d=g.lM(a);!d||b.videoId!==d.videoId||a.TY?(this.player.Kn(b.videoId,void 0,void 0,!0,!0,b),c&&c.EG("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.vT.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.vT.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.lw()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){yhb(this);this.C&&xhb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new g6(this.player):this.endScreen=new l6(this.player),g.I(this,this.endScreen),g.GS(this.player,this.endScreen.element,4))};g.uT("endscreen",zhb);})(_yt_player);
