(function(g){var window=this;'use strict';var lib=function(a){g.V.call(this,{G:"div",N:"ytp-inline-preview-ui"});this.ag=!1;this.player=a;this.S(a,"onStateChange",this.xP);this.S(a,"videodatachange",this.zw);this.S(a,"onInlinePreviewModeChange",this.E4);this.lf=new g.Ap(this.Hv,null,this);g.I(this,this.lf)},y6=function(a){g.vT.call(this,a);
this.j=new lib(this.player);g.I(this,this.j);this.j.hide();g.GS(this.player,this.j.element,4);a.isInline()&&(this.load(),a=a.getRootNode(),g.Lp(a,["ytp-inline-preview-mode","ytp-no-contextmenu"]))};
g.w(lib,g.V);g.k=lib.prototype;
g.k.BM=function(){this.tooltip=new g.UV(this.player,this);g.I(this,this.tooltip);g.GS(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Pc=new g.dU(this.player);g.I(this,this.Pc);this.Uj=new g.V({G:"div",Ia:["ytp-inline-preview-scrim"]});g.I(this,this.Uj);this.Uj.Ea(this.element);this.S(this.Uj.element,"click",this.fH);this.tj=new g.NV(this.player,this,300);g.I(this,this.tj);this.tj.Ea(this.Uj.element);this.controls=new g.V({G:"div",N:"ytp-inline-preview-controls"});g.I(this,this.controls);
this.controls.Ea(this.element);var a=new g.dV(this.player,this,this.player.V().K("kevlar_simp_remove_min_width_for_mute_button"));g.I(this,a);a.Ea(this.controls.element);a=new g.LV(this.player,this);g.I(this,a);a.Ea(this.controls.element);this.Jc=new g.kV(this.player,this);g.I(this,this.Jc);g.GS(this.player,this.Jc.element,4);this.S(this.player,"appresize",this.Db);this.S(this.player,"fullscreentoggled",this.Db);this.Db()};
g.k.show=function(){g.Bp(this.lf);this.ag||(this.BM(),this.ag=!0);0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.Jc.show();this.player.Na("onInlinePreviewUiReady")};
g.k.hide=function(){this.lf.stop();g.V.prototype.hide.call(this);this.player.isInline()||this.ag&&this.Jc.hide()};
g.k.qa=function(){g.V.prototype.qa.call(this)};
g.k.fH=function(a){a.target===this.Uj.element&&this.player.Na("onExpandInlinePreview",a)};
g.k.E4=function(){g.Op(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Ge=function(){this.Jc.xc();this.tj.xc()};
g.k.Hv=function(){this.Ge();g.Bp(this.lf)};
g.k.Db=function(){g.wV(this.Jc,0,this.player.jb().getPlayerSize().width,!1);g.lV(this.Jc)};
g.k.xP=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.zw=function(a,b){if(this.player.isInline()){g.Op(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.eJ);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.Op(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Hc=function(){return this.tooltip};
g.k.xg=function(){return!1};
g.k.Vg=function(){return!1};
g.k.Ub=function(){return!1};
g.k.Pl=function(){return!1};
g.k.cI=function(){};
g.k.Op=function(){};
g.k.py=function(){};
g.k.Nm=function(){return null};
g.k.PF=function(){return null};
g.k.TL=function(){return new g.ze(0,0)};
g.k.zk=function(){return new g.ym(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Uv=function(a,b,c,d,e){var f=d=0,h=0,l=g.Mm(a);if(b){c=g.Jp(b,"ytp-mute-button");var m=g.Jp(b,"ytp-subtitles-button"),n=g.Km(b,this.element);b=g.Mm(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.jb().getPlayerSize().width;h=g.te(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.tp=function(){};
g.k.Hl=function(){return!1};
g.k.TD=function(){};
g.k.Tz=function(){};
g.k.Uq=function(){};
g.k.Tq=function(){};
g.k.aB=function(){};
g.k.Wr=function(){};
g.k.GD=function(){};g.w(y6,g.vT);y6.prototype.Tk=function(){return!1};
y6.prototype.load=function(){this.player.hideControls();this.j.show()};
y6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.uT("inline_preview",y6);})(_yt_player);
